--------------------------------------------------------------------------------
-- DBT MODEL VERIFICATION SCRIPT
-- Purpose: Verify all dbt models exist in Snowflake and contain data
-- Task: #21 - Run Snowflake models to build marts
-- Target: DBT_DEMO.DEV schema
--------------------------------------------------------------------------------

-- Set context
USE DATABASE DBT_DEMO;
USE SCHEMA DEV;
USE WAREHOUSE COMPUTE_WH;

--------------------------------------------------------------------------------
-- SECTION 1: VERIFY ALL VIEWS EXIST
--------------------------------------------------------------------------------
SELECT '=== SECTION 1: VIEW EXISTENCE CHECK ===' AS section;

SELECT 
    COUNT(*) AS total_views,
    COUNT(CASE WHEN table_type = 'VIEW' THEN 1 END) AS confirmed_views
FROM DBT_DEMO.INFORMATION_SCHEMA.TABLES
WHERE table_schema = 'DEV'
  AND table_name IN (
    -- STAGING LAYER (10 models)
    'STG_BENCHMARKS',
    'STG_CASHFLOWS',
    'STG_COUNTERPARTIES',
    'STG_DATES',
    'STG_FUND_STRUCTURES',
    'STG_INSTRUMENTS',
    'STG_PORTFOLIOS',
    'STG_POSITIONS',
    'STG_TRADES',
    'STG_VALUATIONS',
    -- INTERMEDIATE LAYER (8 models)
    'INT_BENCHMARK_RETURNS',
    'INT_CASHFLOW_ENRICHED',
    'INT_DAILY_POSITIONS',
    'INT_FUND_NAV',
    'INT_IRR_CALCULATIONS',
    'INT_PORTFOLIO_ATTRIBUTION',
    'INT_TRADE_ENRICHED',
    'INT_VALUATION_ENRICHED',
    -- MARTS LAYER (10 models)
    'FACT_CASHFLOW_WATERFALL',
    'FACT_FUND_PERFORMANCE',
    'FACT_PORTFOLIO_ATTRIBUTION',
    'FACT_PORTFOLIO_PNL',
    'FACT_PORTFOLIO_SUMMARY',
    'FACT_TRADE_ACTIVITY',
    'REPORT_DAILY_PNL',
    'REPORT_IC_DASHBOARD',
    'REPORT_LP_QUARTERLY',
    'REPORT_PORTFOLIO_OVERVIEW'
  );

-- Expected: total_views = 28, confirmed_views = 28

--------------------------------------------------------------------------------
-- SECTION 2: DETAILED VIEW LIST WITH METADATA
--------------------------------------------------------------------------------
SELECT '=== SECTION 2: DETAILED VIEW LIST ===' AS section;

SELECT 
    table_name,
    table_type,
    row_count,
    bytes,
    CASE 
        WHEN table_name LIKE 'STG_%' THEN '1_STAGING'
        WHEN table_name LIKE 'INT_%' THEN '2_INTERMEDIATE'
        WHEN table_name LIKE 'FACT_%' THEN '3_MARTS_FACT'
        WHEN table_name LIKE 'REPORT_%' THEN '3_MARTS_REPORT'
        ELSE '4_OTHER'
    END AS layer,
    created AS created_timestamp,
    last_altered AS last_modified
FROM DBT_DEMO.INFORMATION_SCHEMA.TABLES
WHERE table_schema = 'DEV'
  AND table_name IN (
    'STG_BENCHMARKS', 'STG_CASHFLOWS', 'STG_COUNTERPARTIES', 'STG_DATES',
    'STG_FUND_STRUCTURES', 'STG_INSTRUMENTS', 'STG_PORTFOLIOS', 'STG_POSITIONS',
    'STG_TRADES', 'STG_VALUATIONS',
    'INT_BENCHMARK_RETURNS', 'INT_CASHFLOW_ENRICHED', 'INT_DAILY_POSITIONS',
    'INT_FUND_NAV', 'INT_IRR_CALCULATIONS', 'INT_PORTFOLIO_ATTRIBUTION',
    'INT_TRADE_ENRICHED', 'INT_VALUATION_ENRICHED',
    'FACT_CASHFLOW_WATERFALL', 'FACT_FUND_PERFORMANCE', 'FACT_PORTFOLIO_ATTRIBUTION',
    'FACT_PORTFOLIO_PNL', 'FACT_PORTFOLIO_SUMMARY', 'FACT_TRADE_ACTIVITY',
    'REPORT_DAILY_PNL', 'REPORT_IC_DASHBOARD', 'REPORT_LP_QUARTERLY',
    'REPORT_PORTFOLIO_OVERVIEW'
  )
ORDER BY layer, table_name;

--------------------------------------------------------------------------------
-- SECTION 3: STAGING LAYER ROW COUNTS
--------------------------------------------------------------------------------
SELECT '=== SECTION 3: STAGING LAYER ROW COUNTS ===' AS section;

SELECT 'STG_BENCHMARKS' AS model, COUNT(*) AS row_count FROM STG_BENCHMARKS
UNION ALL
SELECT 'STG_CASHFLOWS', COUNT(*) FROM STG_CASHFLOWS
UNION ALL
SELECT 'STG_COUNTERPARTIES', COUNT(*) FROM STG_COUNTERPARTIES
UNION ALL
SELECT 'STG_DATES', COUNT(*) FROM STG_DATES
UNION ALL
SELECT 'STG_FUND_STRUCTURES', COUNT(*) FROM STG_FUND_STRUCTURES
UNION ALL
SELECT 'STG_INSTRUMENTS', COUNT(*) FROM STG_INSTRUMENTS
UNION ALL
SELECT 'STG_PORTFOLIOS', COUNT(*) FROM STG_PORTFOLIOS
UNION ALL
SELECT 'STG_POSITIONS', COUNT(*) FROM STG_POSITIONS
UNION ALL
SELECT 'STG_TRADES', COUNT(*) FROM STG_TRADES
UNION ALL
SELECT 'STG_VALUATIONS', COUNT(*) FROM STG_VALUATIONS
ORDER BY model;

-- Expected: Should match seed data counts

--------------------------------------------------------------------------------
-- SECTION 4: INTERMEDIATE LAYER ROW COUNTS
--------------------------------------------------------------------------------
SELECT '=== SECTION 4: INTERMEDIATE LAYER ROW COUNTS ===' AS section;

SELECT 'INT_BENCHMARK_RETURNS' AS model, COUNT(*) AS row_count FROM INT_BENCHMARK_RETURNS
UNION ALL
SELECT 'INT_CASHFLOW_ENRICHED', COUNT(*) FROM INT_CASHFLOW_ENRICHED
UNION ALL
SELECT 'INT_DAILY_POSITIONS', COUNT(*) FROM INT_DAILY_POSITIONS
UNION ALL
SELECT 'INT_FUND_NAV', COUNT(*) FROM INT_FUND_NAV
UNION ALL
SELECT 'INT_IRR_CALCULATIONS', COUNT(*) FROM INT_IRR_CALCULATIONS
UNION ALL
SELECT 'INT_PORTFOLIO_ATTRIBUTION', COUNT(*) FROM INT_PORTFOLIO_ATTRIBUTION
UNION ALL
SELECT 'INT_TRADE_ENRICHED', COUNT(*) FROM INT_TRADE_ENRICHED
UNION ALL
SELECT 'INT_VALUATION_ENRICHED', COUNT(*) FROM INT_VALUATION_ENRICHED
ORDER BY model;

--------------------------------------------------------------------------------
-- SECTION 5: MARTS LAYER ROW COUNTS
--------------------------------------------------------------------------------
SELECT '=== SECTION 5: MARTS LAYER ROW COUNTS ===' AS section;

SELECT 'FACT_CASHFLOW_WATERFALL' AS model, COUNT(*) AS row_count FROM FACT_CASHFLOW_WATERFALL
UNION ALL
SELECT 'FACT_FUND_PERFORMANCE', COUNT(*) FROM FACT_FUND_PERFORMANCE
UNION ALL
SELECT 'FACT_PORTFOLIO_ATTRIBUTION', COUNT(*) FROM FACT_PORTFOLIO_ATTRIBUTION
UNION ALL
SELECT 'FACT_PORTFOLIO_PNL', COUNT(*) FROM FACT_PORTFOLIO_PNL
UNION ALL
SELECT 'FACT_PORTFOLIO_SUMMARY', COUNT(*) FROM FACT_PORTFOLIO_SUMMARY
UNION ALL
SELECT 'FACT_TRADE_ACTIVITY', COUNT(*) FROM FACT_TRADE_ACTIVITY
UNION ALL
SELECT 'REPORT_DAILY_PNL', COUNT(*) FROM REPORT_DAILY_PNL
UNION ALL
SELECT 'REPORT_IC_DASHBOARD', COUNT(*) FROM REPORT_IC_DASHBOARD
UNION ALL
SELECT 'REPORT_LP_QUARTERLY', COUNT(*) FROM REPORT_LP_QUARTERLY
UNION ALL
SELECT 'REPORT_PORTFOLIO_OVERVIEW', COUNT(*) FROM REPORT_PORTFOLIO_OVERVIEW
ORDER BY model;

--------------------------------------------------------------------------------
-- SECTION 6: DATA QUALITY CHECKS
--------------------------------------------------------------------------------
SELECT '=== SECTION 6: DATA QUALITY CHECKS ===' AS section;

-- Check for empty views
SELECT 
    'Empty Views Check' AS check_type,
    COUNT(*) AS issue_count
FROM (
    SELECT 'STG_BENCHMARKS' AS view_name, (SELECT COUNT(*) FROM STG_BENCHMARKS) AS cnt
    UNION ALL SELECT 'STG_CASHFLOWS', (SELECT COUNT(*) FROM STG_CASHFLOWS)
    UNION ALL SELECT 'STG_COUNTERPARTIES', (SELECT COUNT(*) FROM STG_COUNTERPARTIES)
    UNION ALL SELECT 'STG_DATES', (SELECT COUNT(*) FROM STG_DATES)
    UNION ALL SELECT 'STG_FUND_STRUCTURES', (SELECT COUNT(*) FROM STG_FUND_STRUCTURES)
    UNION ALL SELECT 'STG_INSTRUMENTS', (SELECT COUNT(*) FROM STG_INSTRUMENTS)
    UNION ALL SELECT 'STG_PORTFOLIOS', (SELECT COUNT(*) FROM STG_PORTFOLIOS)
    UNION ALL SELECT 'STG_POSITIONS', (SELECT COUNT(*) FROM STG_POSITIONS)
    UNION ALL SELECT 'STG_TRADES', (SELECT COUNT(*) FROM STG_TRADES)
    UNION ALL SELECT 'STG_VALUATIONS', (SELECT COUNT(*) FROM STG_VALUATIONS)
    UNION ALL SELECT 'INT_BENCHMARK_RETURNS', (SELECT COUNT(*) FROM INT_BENCHMARK_RETURNS)
    UNION ALL SELECT 'INT_CASHFLOW_ENRICHED', (SELECT COUNT(*) FROM INT_CASHFLOW_ENRICHED)
    UNION ALL SELECT 'INT_DAILY_POSITIONS', (SELECT COUNT(*) FROM INT_DAILY_POSITIONS)
    UNION ALL SELECT 'INT_FUND_NAV', (SELECT COUNT(*) FROM INT_FUND_NAV)
    UNION ALL SELECT 'INT_IRR_CALCULATIONS', (SELECT COUNT(*) FROM INT_IRR_CALCULATIONS)
    UNION ALL SELECT 'INT_PORTFOLIO_ATTRIBUTION', (SELECT COUNT(*) FROM INT_PORTFOLIO_ATTRIBUTION)
    UNION ALL SELECT 'INT_TRADE_ENRICHED', (SELECT COUNT(*) FROM INT_TRADE_ENRICHED)
    UNION ALL SELECT 'INT_VALUATION_ENRICHED', (SELECT COUNT(*) FROM INT_VALUATION_ENRICHED)
    UNION ALL SELECT 'FACT_CASHFLOW_WATERFALL', (SELECT COUNT(*) FROM FACT_CASHFLOW_WATERFALL)
    UNION ALL SELECT 'FACT_FUND_PERFORMANCE', (SELECT COUNT(*) FROM FACT_FUND_PERFORMANCE)
    UNION ALL SELECT 'FACT_PORTFOLIO_ATTRIBUTION', (SELECT COUNT(*) FROM FACT_PORTFOLIO_ATTRIBUTION)
    UNION ALL SELECT 'FACT_PORTFOLIO_PNL', (SELECT COUNT(*) FROM FACT_PORTFOLIO_PNL)
    UNION ALL SELECT 'FACT_PORTFOLIO_SUMMARY', (SELECT COUNT(*) FROM FACT_PORTFOLIO_SUMMARY)
    UNION ALL SELECT 'FACT_TRADE_ACTIVITY', (SELECT COUNT(*) FROM FACT_TRADE_ACTIVITY)
    UNION ALL SELECT 'REPORT_DAILY_PNL', (SELECT COUNT(*) FROM REPORT_DAILY_PNL)
    UNION ALL SELECT 'REPORT_IC_DASHBOARD', (SELECT COUNT(*) FROM REPORT_IC_DASHBOARD)
    UNION ALL SELECT 'REPORT_LP_QUARTERLY', (SELECT COUNT(*) FROM REPORT_LP_QUARTERLY)
    UNION ALL SELECT 'REPORT_PORTFOLIO_OVERVIEW', (SELECT COUNT(*) FROM REPORT_PORTFOLIO_OVERVIEW)
) AS view_counts
WHERE cnt = 0;

-- Expected: issue_count = 0 (no empty views)

--------------------------------------------------------------------------------
-- SECTION 7: SAMPLE DATA FROM KEY MARTS
--------------------------------------------------------------------------------
SELECT '=== SECTION 7: SAMPLE DATA - REPORT_PORTFOLIO_OVERVIEW ===' AS section;

SELECT *
FROM REPORT_PORTFOLIO_OVERVIEW
LIMIT 5;

SELECT '=== SECTION 7: SAMPLE DATA - FACT_PORTFOLIO_SUMMARY ===' AS section;

SELECT *
FROM FACT_PORTFOLIO_SUMMARY
LIMIT 5;

SELECT '=== SECTION 7: SAMPLE DATA - REPORT_IC_DASHBOARD ===' AS section;

SELECT *
FROM REPORT_IC_DASHBOARD
LIMIT 5;

--------------------------------------------------------------------------------
-- SECTION 8: SUMMARY REPORT
--------------------------------------------------------------------------------
SELECT '=== SECTION 8: FINAL SUMMARY ===' AS section;

SELECT 
    'STAGING' AS layer,
    10 AS expected_models,
    (SELECT COUNT(*) FROM DBT_DEMO.INFORMATION_SCHEMA.TABLES 
     WHERE table_schema = 'DEV' AND table_name LIKE 'STG_%') AS actual_models
UNION ALL
SELECT 
    'INTERMEDIATE',
    8,
    (SELECT COUNT(*) FROM DBT_DEMO.INFORMATION_SCHEMA.TABLES 
     WHERE table_schema = 'DEV' AND table_name LIKE 'INT_%')
UNION ALL
SELECT 
    'MARTS',
    10,
    (SELECT COUNT(*) FROM DBT_DEMO.INFORMATION_SCHEMA.TABLES 
     WHERE table_schema = 'DEV' AND (table_name LIKE 'FACT_%' OR table_name LIKE 'REPORT_%'))
UNION ALL
SELECT 
    '──────────────',
    NULL,
    NULL
UNION ALL
SELECT 
    'TOTAL',
    28,
    (SELECT COUNT(*) FROM DBT_DEMO.INFORMATION_SCHEMA.TABLES 
     WHERE table_schema = 'DEV' 
       AND (table_name LIKE 'STG_%' OR table_name LIKE 'INT_%' 
            OR table_name LIKE 'FACT_%' OR table_name LIKE 'REPORT_%'));

--------------------------------------------------------------------------------
-- SUCCESS CRITERIA CHECKLIST
--------------------------------------------------------------------------------
SELECT '=== SUCCESS CRITERIA ===' AS section;

SELECT 
    '✓ All 28 models executed successfully' AS criteria,
    CASE WHEN (SELECT COUNT(*) FROM DBT_DEMO.INFORMATION_SCHEMA.TABLES 
               WHERE table_schema = 'DEV' AND table_name IN (
                 'STG_BENCHMARKS', 'STG_CASHFLOWS', 'STG_COUNTERPARTIES', 'STG_DATES',
                 'STG_FUND_STRUCTURES', 'STG_INSTRUMENTS', 'STG_PORTFOLIOS', 'STG_POSITIONS',
                 'STG_TRADES', 'STG_VALUATIONS', 'INT_BENCHMARK_RETURNS', 'INT_CASHFLOW_ENRICHED',
                 'INT_DAILY_POSITIONS', 'INT_FUND_NAV', 'INT_IRR_CALCULATIONS',
                 'INT_PORTFOLIO_ATTRIBUTION', 'INT_TRADE_ENRICHED', 'INT_VALUATION_ENRICHED',
                 'FACT_CASHFLOW_WATERFALL', 'FACT_FUND_PERFORMANCE', 'FACT_PORTFOLIO_ATTRIBUTION',
                 'FACT_PORTFOLIO_PNL', 'FACT_PORTFOLIO_SUMMARY', 'FACT_TRADE_ACTIVITY',
                 'REPORT_DAILY_PNL', 'REPORT_IC_DASHBOARD', 'REPORT_LP_QUARTERLY',
                 'REPORT_PORTFOLIO_OVERVIEW'
               )) = 28 
         THEN '✅ PASS' 
         ELSE '❌ FAIL' 
    END AS status
UNION ALL
SELECT 
    '✓ All marts views exist in DBT_DEMO.DEV',
    CASE WHEN (SELECT COUNT(*) FROM DBT_DEMO.INFORMATION_SCHEMA.TABLES 
               WHERE table_schema = 'DEV' 
               AND (table_name LIKE 'FACT_%' OR table_name LIKE 'REPORT_%')) = 10
         THEN '✅ PASS'
         ELSE '❌ FAIL'
    END
UNION ALL
SELECT 
    '✓ Views are materialized correctly',
    CASE WHEN (SELECT COUNT(*) FROM DBT_DEMO.INFORMATION_SCHEMA.TABLES 
               WHERE table_schema = 'DEV' 
               AND table_type = 'VIEW'
               AND table_name IN (
                 'STG_BENCHMARKS', 'STG_CASHFLOWS', 'STG_COUNTERPARTIES', 'STG_DATES',
                 'STG_FUND_STRUCTURES', 'STG_INSTRUMENTS', 'STG_PORTFOLIOS', 'STG_POSITIONS',
                 'STG_TRADES', 'STG_VALUATIONS', 'INT_BENCHMARK_RETURNS', 'INT_CASHFLOW_ENRICHED',
                 'INT_DAILY_POSITIONS', 'INT_FUND_NAV', 'INT_IRR_CALCULATIONS',
                 'INT_PORTFOLIO_ATTRIBUTION', 'INT_TRADE_ENRICHED', 'INT_VALUATION_ENRICHED',
                 'FACT_CASHFLOW_WATERFALL', 'FACT_FUND_PERFORMANCE', 'FACT_PORTFOLIO_ATTRIBUTION',
                 'FACT_PORTFOLIO_PNL', 'FACT_PORTFOLIO_SUMMARY', 'FACT_TRADE_ACTIVITY',
                 'REPORT_DAILY_PNL', 'REPORT_IC_DASHBOARD', 'REPORT_LP_QUARTERLY',
                 'REPORT_PORTFOLIO_OVERVIEW'
               )) = 28
         THEN '✅ PASS'
         ELSE '❌ FAIL'
    END;

--------------------------------------------------------------------------------
-- END OF VERIFICATION SCRIPT
--------------------------------------------------------------------------------
