name: 'bain_capital_analytics'
version: '1.0.0'
config-version: 2

profile: 'bain_capital_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  bain_capital_analytics:
    +schema: raw

models:
  bain_capital_analytics:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: view
