bain_capital_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5433
      user: "{{ env_var('DBT_PG_USER', 'postgres') }}"
      password: "{{ env_var('DBT_PG_PASSWORD', 'postgres') }}"
      dbname: "{{ env_var('DBT_PG_DBNAME', 'bain_analytics') }}"
      schema: public
      threads: 4
